### ISSUE TITLE
 Error executing lua [string ":lua"]:1: module 'cmp' not found

### ISSUE THREAD

**Issue by maitra** [R-nvim/cmp-r#4]
I have the following in my `.config/nvim/init.vim` file:

```
call plug#begin('~/.vim/plugged')

Plug 'bluz71/vim-nightfly-colors'
Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-rsi'
Plug 'mhartington/formatter.nvim'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1

Plug 'lervag/vimtex'
" Track the engine.
Plug 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plug 'honza/vim-snippets'

Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'R-nvim/R.nvim'
Plug 'R-nvim/cmp-r'

:lua << EOF
require'cmp'.setup {
  sources = {
    { name = 'cmp_r' },
  }
}
EOF

call plug#end()

```

However, when I load a file (say code.R), I get the following errors:

```
E5108: Error executing lua [string ":lua"]:1: module 'cmp' not found:
        no field package.preload['cmp']
        no file './cmp.lua'
        no file '/usr/share/luajit-2.1/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp.lua'
        no file '/usr/local/share/lua/5.1/cmp/init.lua'
        no file '/usr/share/lua/5.1/cmp.lua'
        no file '/usr/share/lua/5.1/cmp/init.lua'
        no file './cmp.so'
        no file '/usr/local/lib/lua/5.1/cmp.so'
        no file '/usr/lib64/lua/5.1/cmp.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
Error detected while processing BufNewFile Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:24: Error executing lua: /usr/share/nvim/runtime/filetype.lua:25: BufNewFile Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[19]..script /home/maitra/.vim/plugged/R.nvim/ftplugin/r_rnvim.lua: Vim(runtime):E5113: Error while calling lua chunk: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'r' language, see :help treesitter-parsers 
stack traceback:
        [C]: in function 'error'
        /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:93: in function 'add'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'parse'
        /home/maitra/.vim/plugged/R.nvim/lua/r/send.lua:642: in main chunk
        [C]: in function 'require'
        /home/maitra/.vim/plugged/R.nvim/lua/r/run.lua:7: in main chunk
        [C]: in function 'require'
        /home/maitra/.vim/plugged/R.nvim/lua/r/config.lua:739: in function 'global_setup'
        /home/maitra/.vim/plugged/R.nvim/lua/r/config.lua:803: in function 'real_setup'
        /home/maitra/.vim/plugged/R.nvim/ftplugin/r_rnvim.lua:12: in main chunk
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:25: in function </usr/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>

```

What is causing the error?  How do I get around this? I am on Fedora 39 and neovim 0.9.5. Thanks!

**Comment by jalvesaq** [comment]
Your code seems to be correct, but `lazy.nvim` calls the `setup()` function of plugins automatically. You could try to call the setup of `R.nvim` and `cmp-r` manually:

```
:lua << EOF
require("cmp").setup({ sources = {{ name = "cmp_r" }}})
require("cmp_r").setup()
require("r").setup()
EOF
```

**Comment by jalvesaq** [comment]
Maybe the chunk `:lua << EOF ... EOF` should be **after** `call plug#end()`.

I updated the "minimal" example of https://github.com/R-nvim/R.nvim/wiki/Configuration

Then, trying to adapt it to your `init.vim`:

```
:lua << EOF
require("nvim-treesitter.configs").setup({
  sync_install = true,
  ensure_installed = {
    "r",
    "markdown",
    "markdown_inline",
    "rnoweb",
  },
})

local cmp = require("cmp")
cmp.setup({
  sources = {{ name = "cmp_r" }},
  mapping = cmp.mapping.preset.insert({
    ['<CR>'] = cmp.mapping.confirm({ select = false }),
    -- During auto-completion, press <Tab> to select the next item.
    ['<Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_next_item({ behavior = cmp.SelectBehavior.Insert })
      elseif has_words_before() then
        cmp.complete()
      else
        fallback()
      end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item({ behavior = cmp.SelectBehavior.Insert })
      else
        fallback()
      end
    end, { 'i', 's' }),
  }),
})

require("cmp_r").setup({ })
EOF
```

**Comment by maitra** [comment]
Thank you for looking into this! I now get a different error:

```

Error executing vim.schedule lua callback: /home/maitra/.vim/plugged/R.nvim/lua/r/server.lua:73: att
empt to concatenate upvalue 'libd' (a nil value)
stack traceback:
        /home/maitra/.vim/plugged/R.nvim/lua/r/server.lua:73: in function </home/maitra/.vim/plugged
/R.nvim/lua/r/server.lua:71>
```

**Comment by maitra** [comment]
Thanks! My R is installed on my Fedora 39 system. Packages have all been installed earlier. I just did `nvim code.R` (where `code.R` was a new file. How do I get around this error while editing R's script? Thanks very much again!

**Comment by jalvesaq** [comment]
I'm trying to fix it...

**Comment by maitra** [comment]
So, my plugin installations are in `~/vimfiles/plugged` and that is writable. Am I answering your question here? Thanks!

**Comment by jalvesaq** [comment]
No. The directory where nvimcom is going to be installed is something like `~/R/x86_64-pc-linux-gnu-library/4.3` or, more precisely, the output of `Sys.getenv("R_LIBS_USER")`.

**Comment by maitra** [comment]
Oh, I see, sorry. Yes, it is writable: however, I usually install systemwide using `sudo R` when needed (but that is not relevant to your question).
```
> Sys.getenv("R_LIBS_USER")
[1] "/home/maitra/R/x86_64-redhat-linux-gnu-library/4.3"
```
Is there a way to skip this local installation step?

**Comment by maitra** [comment]
I should add that the directory `/home/maitra/R/` exists and is writable, however, there is nothing in there. Perhaps that is an issue?

**Comment by jalvesaq** [comment]
It's incomplete. The "x86.../4.3" is missing

**Comment by maitra** [comment]
> It's incomplete. The "x86.../4.3" is missing
I see. So, I create the directory, and the error goes away! However, the assignment does not work. 

`x_2` does not switch to `x <- 2` in the edit phase.

**Comment by jalvesaq** [comment]
I have to go out now...

Did you set assign_map?

**Comment by jalvesaq** [comment]
The default has changed.

**Comment by jalvesaq** [comment]
Where you have:

```lua
require("cmp_r").setup({ })
```

you need:

```lua
require("cmp_r").setup({ })
require("r").setup({ assign_map = "_" })
```

**Comment by jalvesaq** [comment]
> I see. So, I create the directory, and the error goes away!

I have fixed the bug that was preventing `R.nvim` from creating the directory. Could you, please, manually delete the directory `~/R/x86_64-redhat-linux-gnu-library/4.3` to confirm that `R.nvim` now succeeds when trying to create it?

**Comment by maitra** [comment]
> > I see. So, I create the directory, and the error goes away!
> 
> I have fixed the bug that was preventing `R.nvim` from creating the directory. Could you, please, manually delete the directory `~/R/x86_64-redhat-linux-gnu-library/4.3` to confirm that `R.nvim` now succeeds when trying to create it?

Yes, this works! Btw, is it possible to install nvimcom systemwide (and not have this directory at all), or is it needed for nvim-R to function?

**Comment by jalvesaq** [comment]
Thanks for testing it!

> Btw, is it possible to install nvimcom systemwide

I have never installed it systemwide, but, yes: https://github.com/jalvesaq/Nvim-R/issues/735

**Comment by maitra** [comment]
> Where you have:
> 
> ```lua
> require("cmp_r").setup({ })
> ```
> 
> you need:
> 
> ```lua
> require("cmp_r").setup({ })
> require("r").setup({ assign_map = "_" })
> ```

So, I tried this, and I was expecting that when I did

`x_5` then it would automatically become `x <- 5` in my R source code. However, that is not happening and it says `x_5` in my R script.

**Comment by maitra** [comment]
Btw, I still have the error when I hit 'tab' in my R script file.

```
E5108: Error executing lua: [string ":lua"]:20: attempt to call global 'has_words_before' (a nil val
ue)
stack traceback:
        [string ":lua"]:20: in function 'on_keymap'
        /home/maitra/.vim/plugged/nvim-cmp/lua/cmp/core.lua:145: in function 'callback'
        /home/maitra/.vim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua:133: in function </home/maitra/.
vim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua:127>

```
Where does this come from?
